name: Build Site and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Generate static site
        run: dotnet run --project $GITHUB_WORKSPACE/src/SiteBuilder.csproj $GITHUB_WORKSPACE
        
      - name: Remove site builder
        run: rm src -r

      - name: Deploy static site
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
