name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Generate static site
        run: dotnet run --project $GITHUB_WORKSPACE/src/SiteBuilder.csproj $GITHUB_WORKSPACE